# Generated by Django 3.0.7 on 2020-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200924_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_catagory',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
