# Generated by Django 3.0.7 on 2020-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200924_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_catagory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
