# Generated by Django 3.0.7 on 2020-09-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200924_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Catagory'),
        ),
    ]
