# Generated by Django 3.0.7 on 2020-09-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_catagory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Catagory', unique=True),
        ),
    ]
