# Generated by Django 3.0.7 on 2020-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200924_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
