# Generated by Django 3.0.7 on 2020-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_posts_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_slug',
            new_name='slug',
        ),
    ]
